import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'yossef',
      email: 'admin@test.com',
      password: bcrypt.hashSync('456789'),
      isAdmin: true,
    },
    {
      name: 'nisim',
      email: 'nisim@test.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
    {
      name: 'yoav',
      email: 'yoav@test.com',
      password: bcrypt.hashSync('123123'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'porior slim shirt',
      slug: 'porior-slim-shirt',
      category: 'Shirts',
      image: '/images/t1.webp',
      price: 200,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'timberland shirt',
      slug: 'timberland-slim-shirt1',
      category: 'Shirts',
      image: '/images/t3.webp',
      price: 150,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4,
      numReviews: 11,
      description: 'high quality shirt',
    },
    {
      name: 'nautica slim shirt',
      slug: 'nautica-slim-shirt2',
      category: 'pantes',
      image: '/images/t5.webp',
      price: 150,
      countInStock: 5,
      brand: 'puma',
      rating: 3,
      numReviews: 13,
      description: 'high quality pantes',
    },
    {
      name: 'nautica slim shirt1',
      slug: 'nautica-slim-shirt3',
      category: 'pantes',
      image: '/images/t7.webp',
      price: 300,
      countInStock: 4,
      brand: 'nautica',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pantes',
    },
    {
      name: 'timberland slim pantes',
      slug: 'timberland-slim-pantes1',
      category: 'Shirts',
      image: '/images/t9.webp',
      price: 200,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 4,
      description: 'high quality shirt',
    },
    {
      name: 'castro pantes',
      slug: 'castro-slim-pantes2',
      category: 'Shirts',
      image: '/images/t11.webp',
      price: 150,
      countInStock: 10,
      brand: 'Adidas',
      rating: 1,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'zara slim pantes',
      slug: 'zara-slim-pantes3',
      category: 'pantes',
      image: '/images/t13.webp',
      price: 150,
      countInStock: 5,
      brand: 'puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pantes',
    },
    {
      name: 'diesel slim pantes',
      slug: 'diesel-slim-pantes4',
      category: 'pantes',
      image: '/images/t15.webp',
      price: 300,
      countInStock: 4,
      brand: 'nautica',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pantes',
    },
    {
      name: 'nike slim shirt',
      slug: 'nike-slim-shirt4',
      category: 'Shirts',
      image: '/images/t2.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 23,
      description: 'high quality shirt',
    },
    {
      name: 'adidas shirt',
      slug: 'adidas-slim-shirt5',
      category: 'Shirts',
      image: '/images/t4.webp',
      price: 150,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'puma slim shirt',
      slug: 'puma-slim-shirt6',
      category: 'pantes',
      image: '/images/t6.webp',
      price: 150,
      countInStock: 5,
      brand: 'puma',
      rating: 4,
      numReviews: 15,
      description: 'high quality pantes',
    },
    {
      name: 'nautica slim shirt7',
      slug: 'nautica-slim-shirt7',
      category: 'pantes',
      image: '/images/t8.webp',
      price: 300,
      countInStock: 4,
      brand: 'nautica',
      rating: 3,
      numReviews: 10,
      description: 'high quality pantes',
    },
    {
      name: 'nike slim pantes4',
      slug: 'nike-slim-pantes5',
      category: 'Shirts',
      image: '/images/t10.webp',
      price: 200,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'adidas pantes3',
      slug: 'adidas-slim-pantes6',
      category: 'Shirts',
      image: '/images/t12.webp',
      price: 150,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 6,
      description: 'high quality shirt',
    },
    {
      name: 'puma slim pantes2',
      slug: 'puma-slim-pantes7',
      category: 'pantes',
      image: '/images/t14.webp',
      price: 150,
      countInStock: 5,
      brand: 'puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pantes',
    },
    {
      name: 'nautica slim pantes1',
      slug: 'nautica-slim-pantes8',
      category: 'pantes',
      image: '/images/t16.webp',
      price: 300,
      countInStock: 4,
      brand: 'nautica',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality pantes',
    },
  ],
};

export default data;
