const data = {
  products: [
    {
      name: 'nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'adidas shirt',
      slug: 'adidas-slim-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'puma slim pantes',
      slug: 'puma-slim-pantes',
      category: 'pantes',
      image: '/images/p3.jpg',
      price: 150,
      countInStock: 5,
      brand: 'puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pantes',
    },
    {
      name: 'nautica slim pantes',
      slug: 'nautica-slim-pantes',
      category: 'pantes',
      image: '/images/p4.jpg',
      price: 300,
      countInStock: 4,
      brand: 'nautica',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pantes',
    },
    {
      name: 'nike slim shirt',
      slug: 'nike-slim-shirt2',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'adidas shirt',
      slug: 'adidas-slim-shirt2',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'puma slim pantes',
      slug: 'puma-slim-pantes2',
      category: 'pantes',
      image: '/images/p3.jpg',
      price: 150,
      countInStock: 5,
      brand: 'puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pantes',
    },
    {
      name: 'nautica slim pantes',
      slug: 'nautica-slim-pantes2',
      category: 'pantes',
      image: '/images/p4.jpg',
      price: 300,
      countInStock: 4,
      brand: 'nautica',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pantes',
    },
    {
      name: 'nike slim shirt',
      slug: 'nike-slim-shirt3',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'adidas shirt',
      slug: 'adidas-slim-shirt3',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'puma slim pantes',
      slug: 'puma-slim-pantes3',
      category: 'pantes',
      image: '/images/p3.jpg',
      price: 150,
      countInStock: 5,
      brand: 'puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pantes',
    },
    {
      name: 'nautica slim pantes',
      slug: 'nautica-slim-pantes3',
      category: 'pantes',
      image: '/images/p4.jpg',
      price: 300,
      countInStock: 4,
      brand: 'nautica',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pantes',
    },
    {
      name: 'nike slim shirt',
      slug: 'nike-slim-shirt4',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'adidas shirt',
      slug: 'adidas-slim-shirt4',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'puma slim pantes',
      slug: 'puma-slim-pantes4',
      category: 'pantes',
      image: '/images/p3.jpg',
      price: 150,
      countInStock: 5,
      brand: 'puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pantes',
    },
    {
      name: 'nautica slim pantes',
      slug: 'nautica-slim-pantes4',
      category: 'pantes',
      image: '/images/p4.jpg',
      price: 300,
      countInStock: 4,
      brand: 'nautica',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pantes',
    },
  ],
};

export default data;
